/**
 * The one-switch rule (SOLANA_CLUSTER) and the fail-closed readiness check, against BOTH configurations. Mainnet is only ever an
 * env object here: nothing contacts a network, and every key is generated by the test (never printed, never a real one).
 */
import { describe, expect, it, vi } from 'vitest';
import { Keypair } from '@solana/web3.js';
import { ApiError } from '@/contracts';
import { assertClusterReady, clusterConfig, inspectCluster, reportError, requiredRoleKeys } from '../cluster';
import { CIRCLE_DEVNET_USDC_MINT, DEFAULT_RPC, MAINNET_USDC_MINT } from '../config';
import { explorerAddressUrl, explorerBase, explorerTxUrl } from '../explorer';

const secret = () => JSON.stringify(Array.from(Keypair.generate().secretKey));
const addr = () => Keypair.generate().publicKey.toBase58();
const TEST_MINT = addr();
const FEE = addr();

/** What an operator sets for devnet (and what a bare checkout needs: nothing). */
const DEVNET: Record<string, string> = {
  SOLANA_CLUSTER: 'devnet', SOLANA_RPC_URL: 'https://devnet.rpc-provider.test/key', USDC_MINT: TEST_MINT, PLATFORM_WALLET_ADDRESS: FEE,
  SETTLEMENT_AUTHORITY_SECRET_KEY: secret(), HOUSE_SELLER_SECRET_KEY: secret(), FAUCET_MINT_AUTHORITY_SECRET_KEY: secret(),
};
/** The minimum a mainnet deployment needs: the switch, an RPC, the settlement authority and the fee wallet. */
const MAINNET: Record<string, string> = {
  SOLANA_CLUSTER: 'mainnet-beta', SOLANA_RPC_URL: 'https://mainnet.rpc-provider.test/key', PLATFORM_WALLET_ADDRESS: FEE, SETTLEMENT_AUTHORITY_SECRET_KEY: secret(),
};
const without = (env: Record<string, string>, ...names: string[]) => Object.fromEntries(Object.entries(env).filter(([k]) => !names.includes(k)));

describe('devnet (the default): nothing needs to be set', () => {
  it('an empty environment is devnet and ready', () => {
    expect(inspectCluster({})).toEqual({ cluster: 'devnet', ready: true, missing: [], conflicts: [] });
    const c = clusterConfig({});
    expect(c).toMatchObject({ cluster: 'devnet', mainnet: false, usdcMint: CIRCLE_DEVNET_USDC_MINT, rpcUrls: [DEFAULT_RPC.devnet], explorerBase: explorerBase() });
  });

  it('a full devnet set is ready and resolves to its own values', () => {
    expect(inspectCluster(DEVNET)).toMatchObject({ cluster: 'devnet', ready: true });
    const c = clusterConfig(DEVNET);
    expect(c.usdcMint).toBe(TEST_MINT);
    expect(c.rpcUrls).toEqual(['https://devnet.rpc-provider.test/key', DEFAULT_RPC.devnet]);
    expect(c.feeWallet).toBe(FEE);
    expect(explorerTxUrl('sig', 'devnet')).toBe(`${explorerBase()}/tx/sig?cluster=devnet`);
    expect(explorerAddressUrl('a', 'devnet')).toBe(`${explorerBase()}/address/a?cluster=devnet`);
  });

  it('is refused for values that belong to mainnet: the mainnet mint, a mainnet RPC, the two cluster variables disagreeing', () => {
    expect(inspectCluster({ ...DEVNET, USDC_MINT: MAINNET_USDC_MINT }).conflicts).toEqual(['USDC_MINT']);
    expect(inspectCluster({ ...DEVNET, NEXT_PUBLIC_USDC_MINT: MAINNET_USDC_MINT }).conflicts).toEqual(['NEXT_PUBLIC_USDC_MINT']);
    expect(inspectCluster({ ...DEVNET, SOLANA_RPC_URL: 'https://mainnet.helius-rpc.test/x' }).conflicts).toEqual(['SOLANA_RPC_URL']);
    expect(inspectCluster({ ...DEVNET, NEXT_PUBLIC_SOLANA_NETWORK: 'mainnet-beta' })).toEqual({ cluster: null, ready: false, missing: [], conflicts: ['SOLANA_CLUSTER', 'NEXT_PUBLIC_SOLANA_NETWORK'] });
  });
});

describe('mainnet: the one switch moves everything, and nothing falls back to devnet', () => {
  it('a complete minimum is ready; the USDC mint defaults to the real one, the RPC list ends at the public mainnet endpoint', () => {
    expect(inspectCluster(MAINNET)).toEqual({ cluster: 'mainnet-beta', ready: true, missing: [], conflicts: [] });
    const c = clusterConfig(MAINNET);
    expect(c).toMatchObject({ cluster: 'mainnet-beta', mainnet: true, usdcMint: MAINNET_USDC_MINT, feeWallet: FEE });
    expect(c.rpcUrls).toEqual(['https://mainnet.rpc-provider.test/key', DEFAULT_RPC['mainnet-beta']]);
    expect(JSON.stringify(c)).not.toMatch(/devnet|testnet/i); // no devnet value anywhere in the resolved mainnet config
    expect(explorerTxUrl('sig', 'mainnet-beta')).toBe(`${explorerBase()}/tx/sig`); // mainnet is the explorer's default network
    expect(explorerAddressUrl('a', 'mainnet-beta')).toBe(`${explorerBase()}/address/a`);
  });

  it('the switch alone follows through the other spelling and the explicit real mint', () => {
    expect(inspectCluster({ ...without(MAINNET, 'SOLANA_CLUSTER'), NEXT_PUBLIC_SOLANA_NETWORK: 'mainnet' }).cluster).toBe('mainnet-beta');
    expect(inspectCluster({ ...MAINNET, NEXT_PUBLIC_SOLANA_NETWORK: 'mainnet-beta', USDC_MINT: MAINNET_USDC_MINT, NEXT_PUBLIC_USDC_MINT: MAINNET_USDC_MINT, NEXT_PUBLIC_PLATFORM_WALLET_ADDRESS: FEE }).ready).toBe(true);
  });

  it.each([
    ['the RPC', 'SOLANA_RPC_URL'],
    ['the settlement authority key', 'SETTLEMENT_AUTHORITY_SECRET_KEY'],
    ['the fee wallet', 'PLATFORM_WALLET_ADDRESS'],
  ])('is incomplete without %s, and names exactly that variable', (_label, name) => {
    expect(inspectCluster(without(MAINNET, name))).toEqual({ cluster: 'mainnet-beta', ready: false, missing: [name], conflicts: [] });
  });

  it('is incomplete with an unreadable key, and never echoes its value', () => {
    const junk = 'definitely-not-a-key-0123456789';
    const r = inspectCluster({ ...MAINNET, SETTLEMENT_AUTHORITY_SECRET_KEY: junk });
    expect(r.missing).toEqual(['SETTLEMENT_AUTHORITY_SECRET_KEY']);
    expect(JSON.stringify(r)).not.toContain(junk);
  });

  it('needs the VRF key only while FEATURE_VRF is on', () => {
    expect(requiredRoleKeys('mainnet-beta', {})).toEqual(['SETTLEMENT_AUTHORITY_SECRET_KEY']);
    expect(requiredRoleKeys('mainnet-beta', { FEATURE_VRF: 'true' })).toEqual(['SETTLEMENT_AUTHORITY_SECRET_KEY', 'VRF_SECRET_KEY']);
    expect(requiredRoleKeys('devnet', { FEATURE_VRF: 'true' })).toEqual([]);
    expect(inspectCluster({ ...MAINNET, FEATURE_VRF: 'true' }).missing).toEqual(['VRF_SECRET_KEY']);
    expect(inspectCluster({ ...MAINNET, FEATURE_VRF: 'true', VRF_SECRET_KEY: secret() }).ready).toBe(true);
    expect(inspectCluster({ ...MAINNET, FEATURE_VRF: 'false' }).ready).toBe(true);
  });

  it('needs the VRF key while FEATURE_PACKS is on too (a pack draw is a VRF draw), on mainnet only', () => {
    expect(requiredRoleKeys('mainnet-beta', { FEATURE_PACKS: 'true' })).toEqual(['SETTLEMENT_AUTHORITY_SECRET_KEY', 'VRF_SECRET_KEY']);
    expect(requiredRoleKeys('devnet', { FEATURE_PACKS: 'true' })).toEqual([]);
    expect(inspectCluster({ ...MAINNET, FEATURE_PACKS: 'true' }).missing).toEqual(['VRF_SECRET_KEY']);
    expect(inspectCluster({ ...MAINNET, FEATURE_PACKS: 'true', VRF_SECRET_KEY: secret() }).ready).toBe(true);
    expect(inspectCluster({ ...MAINNET, FEATURE_PACKS: 'false' }).ready).toBe(true);
  });

  it('is refused for values that belong to devnet: a devnet RPC, a test mint, the faucet authority, a different browser network', () => {
    expect(inspectCluster({ ...MAINNET, SOLANA_RPC_URL: 'https://api.devnet.solana.com' }).conflicts).toEqual(['SOLANA_RPC_URL']);
    expect(inspectCluster({ ...MAINNET, SOLANA_RPC_FALLBACK_URLS: 'https://a.example,https://devnet.helius-rpc.test/x' }).conflicts).toEqual(['SOLANA_RPC_FALLBACK_URLS']);
    expect(inspectCluster({ ...MAINNET, NEXT_PUBLIC_SOLANA_RPC_PUBLIC: 'https://api.testnet.solana.com' }).conflicts).toEqual(['NEXT_PUBLIC_SOLANA_RPC_PUBLIC']);
    expect(inspectCluster({ ...MAINNET, USDC_MINT: TEST_MINT }).conflicts).toEqual(['USDC_MINT']);
    expect(inspectCluster({ ...MAINNET, NEXT_PUBLIC_USDC_MINT: CIRCLE_DEVNET_USDC_MINT }).conflicts).toEqual(['NEXT_PUBLIC_USDC_MINT']);
    expect(inspectCluster({ ...MAINNET, FAUCET_MINT_AUTHORITY_SECRET_KEY: secret() }).conflicts).toEqual(['FAUCET_MINT_AUTHORITY_SECRET_KEY']);
    expect(inspectCluster({ ...MAINNET, NEXT_PUBLIC_SOLANA_NETWORK: 'devnet' }).conflicts).toEqual(['SOLANA_CLUSTER', 'NEXT_PUBLIC_SOLANA_NETWORK']);
    expect(inspectCluster({ ...MAINNET, NEXT_PUBLIC_PLATFORM_WALLET_ADDRESS: addr() }).conflicts).toEqual(['PLATFORM_WALLET_ADDRESS']);
  });

  it('refuses a polluted or non-https value as a conflict (a pasted comment once reached production)', () => {
    expect(inspectCluster({ ...MAINNET, SOLANA_RPC_URL: 'https://x.example      # Client-safe (no key)' }).conflicts).toEqual(['SOLANA_RPC_URL']);
    expect(inspectCluster({ ...MAINNET, SOLANA_RPC_URL: 'http://rpc.example' }).conflicts).toEqual(['SOLANA_RPC_URL']);
    expect(inspectCluster({ ...MAINNET, PLATFORM_WALLET_ADDRESS: `${FEE} # fee` }).conflicts).toEqual(['PLATFORM_WALLET_ADDRESS']);
  });
});

describe('fail closed: the 503 that health and every money route answer', () => {
  it('turns a report into the right ApiError, names only', () => {
    expect(reportError(inspectCluster(MAINNET))).toBeNull();
    const incomplete = reportError(inspectCluster(without(MAINNET, 'SOLANA_RPC_URL', 'PLATFORM_WALLET_ADDRESS')))!;
    expect(incomplete).toBeInstanceOf(ApiError);
    expect(incomplete).toMatchObject({ code: 'mainnet_config_incomplete', status: 503 });
    expect(incomplete.message).toContain('SOLANA_RPC_URL');
    expect(incomplete.message).toContain('PLATFORM_WALLET_ADDRESS');
    const conflict = reportError(inspectCluster({ ...MAINNET, USDC_MINT: TEST_MINT }))!;
    expect(conflict).toMatchObject({ code: 'cluster_config_conflict', status: 503 });
    expect(conflict.message).not.toContain(TEST_MINT);
    expect(reportError(inspectCluster({ ...MAINNET, NEXT_PUBLIC_SOLANA_NETWORK: 'devnet' }))).toMatchObject({ code: 'cluster_config_conflict' });
  });

  it('assertClusterReady passes a complete config and throws the 503 otherwise', () => {
    vi.spyOn(console, 'error').mockImplementation(() => {});
    expect(() => assertClusterReady(undefined, {})).not.toThrow(); // devnet default
    expect(() => assertClusterReady('mainnet-beta', MAINNET)).not.toThrow();
    expect(() => assertClusterReady('devnet', DEVNET)).not.toThrow();
    expect(() => assertClusterReady(undefined, { SOLANA_CLUSTER: 'mainnet-beta' })).toThrow(expect.objectContaining({ code: 'mainnet_config_incomplete', status: 503 }));
    expect(() => assertClusterReady('mainnet-beta', { ...MAINNET, SOLANA_RPC_URL: 'https://api.devnet.solana.com' })).toThrow(expect.objectContaining({ code: 'cluster_config_conflict' }));
  });

  it('refuses a sale of the other network even when the configuration is complete', () => {
    expect(() => assertClusterReady('devnet', MAINNET)).toThrow(expect.objectContaining({ code: 'cluster_config_conflict', status: 503 }));
    expect(() => assertClusterReady('mainnet-beta', DEVNET)).toThrow(expect.objectContaining({ code: 'cluster_config_conflict', status: 503 }));
  });

  it('logs names only, never a value', () => {
    const log = vi.spyOn(console, 'error').mockImplementation(() => {});
    const env: Record<string, string> = { ...MAINNET, SOLANA_RPC_URL: 'https://api.devnet.solana.com/?api-key=SUPERSECRETKEY' };
    expect(() => assertClusterReady(undefined, env)).toThrow();
    const out = JSON.stringify(log.mock.calls);
    expect(out).toContain('SOLANA_RPC_URL');
    expect(out).not.toContain('SUPERSECRETKEY');
    expect(out).not.toContain(env.SETTLEMENT_AUTHORITY_SECRET_KEY);
    log.mockRestore();
  });
});
